#codung: utf-8
SUBSCRIPTION_UNWATCHED = 0
SUBSCRIPTION_WATCHING = 1
SUBSCRIPTION_WATCHED = 2
SUBSCRIPTION_FORGONE = 3
SUBSCRIPTION_STATUS = (
    (SUBSCRIPTION_UNWATCHED, 'unwatch'),
    (SUBSCRIPTION_WATCHING, 'watching'),
    (SUBSCRIPTION_WATCHED, 'watched'),
    (SUBSCRIPTION_FORGONE, 'forgone'),
)

BANGUMI_END = 0
BANGUMI_NOT_END = 1
BANGUMI_END_STATUS = (
    (BANGUMI_END, 'end'),
    (BANGUMI_NOT_END, 'not end')
)